variables:
  service_name: gp-connect-second-generation
  short_service_name: gcsg
  service_base_path: gp-connect-second-generation
  test-variables: |
      PROXY_NAME=$(FULLY_QUALIFIED_SERVICE_NAME) \
      SOURCE_COMMIT_ID=$(Build.SourceVersion) \
      APIGEE_ACCESS_TOKEN=$(secret.AccessToken) \
      APIGEE_APP_ID= \
      STATUS_ENDPOINT_API_KEY=$(STATUS_ENDPOINT_API_KEY) \