variables:
  - group: status-endpoint
  - name: service_name
    value: gp-connect-second-generation
  - name: short_service_name
    value: gcsg
  - name: service_base_path
    value: gp-connect-second-generation