variables:
  service_name: {{ SERVICE_NAME }}
  short_service_name: {{ SHORT_SERVICE_NAME }}
  service_base_path: {{ SERVICE_BASE_PATH }}
  test-variables: |
      PROXY_NAME=$(FULLY_QUALIFIED_SERVICE_NAME) \
      SOURCE_COMMIT_ID=$(Build.SourceVersion) \
      APIGEE_ACCESS_TOKEN=$(secret.AccessToken) \
      APIGEE_APP_ID= \
      STATUS_ENDPOINT_API_KEY=$(STATUS_ENDPOINT_API_KEY) \